In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import sys
!"{sys.executable}" -m pip install apyori
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

Requirement already satisfied: apyori in c:\users\anmol patel\anaconda3\envs\gpuenv\lib\site-packages (1.1.2)

In [3]:
dataset = pd.read_csv('netflix_data.csv', header = None , encoding="latin1")
transactions = []

for i in range(0, 7466):
    transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])

In [4]:
print(dataset)

                            0                   1   \
0        The Lord of the rings     Cinema Paradiso
1     The Shawshank Redemption          Fight Club
2                The Godfather                 NaN
3       The Godfather: Part II               Se7en
4              The Dark Knight    The Intouchables
...                        ...                 ...
7463             Prision Break                 NaN
7464            Harry Potter 2            Whiplash
7465              Pulp Fiction  Back to the Future
7466                       NaN                 NaN
7467                       NaN                 NaN

                                      2   \
0                                  Se7en
1                           Pulp Fiction
2                                    NaN
3                                    NaN
4        One Flew Over the Cuckoo's Nest
...                                  ...
7463                                 NaN
7464                                 NaN
7465  Star Wars: Episode IV - A New Hope
7466                                 NaN
7467                                 NaN

                                                     3            4   \
0                                Avengers: Infinity War  The Shining
1                                                   NaN          NaN
2                                                   NaN          NaN
3                                                   NaN          NaN
4     whole wheat Star Wars: Episode V - The Empire ...     Whiplash
...                                                 ...          ...
7463                                                NaN          NaN
7464                                                NaN          NaN
7465                                       12 Angry Men          NaN
7466                                                NaN          NaN
7467                                                NaN          NaN

                 5                           6          7            8   \
0     High and Low   Terminator 2: Judgment Day  Toy Story  City of God
1               NaN                         NaN        NaN          NaN
2               NaN                         NaN        NaN          NaN
3               NaN                         NaN        NaN          NaN
4               NaN                         NaN        NaN          NaN
...             ...                         ...        ...          ...
7463            NaN                         NaN        NaN          NaN
7464            NaN                         NaN        NaN          NaN
7465            NaN                         NaN        NaN          NaN
7466            NaN                         NaN        NaN          NaN
7467            NaN                         NaN        NaN          NaN

                               9   ...             12        13  \
0     Witness for the Prosecution  ...  Black Panther  Hamilton
1                             NaN  ...            NaN       NaN
2                             NaN  ...            NaN       NaN
3                             NaN  ...            NaN       NaN
4                             NaN  ...            NaN       NaN
...                           ...  ...            ...       ...
7463                          NaN  ...            NaN       NaN
7464                          NaN  ...            NaN       NaN
7465                          NaN  ...            NaN       NaN
7466                          NaN  ...            NaN       NaN
7467                          NaN  ...            NaN       NaN

                   14                            15                  16  \
0     The Dark Knight  Once Upon a Time in the West  The Great Dictator
1                 NaN                           NaN                 NaN
2                 NaN                           NaN                 NaN
3                 NaN                           NaN                 NaN
4                 NaN                           NaN                 NaN
...               ...                           ...                 ...
7463              NaN                           NaN                 NaN
7464              NaN                           NaN                 NaN
7465              NaN                           NaN                 NaN
7466              NaN                           NaN                 NaN
7467              NaN                           NaN                 NaN

                      17      18                        19  20  21
0     Back to the Future  Aliens  Comedy nights with Kapil NaN NaN
1                    NaN     NaN                       NaN NaN NaN
2                    NaN     NaN                       NaN NaN NaN
3                    NaN     NaN                       NaN NaN NaN
4                    NaN     NaN                       NaN NaN NaN
...                  ...     ...                       ...  ..  ..
7463                 NaN     NaN                       NaN NaN NaN
7464                 NaN     NaN                       NaN NaN NaN
7465                 NaN     NaN                       NaN NaN NaN
7466                 NaN     NaN                       NaN NaN NaN
7467                 NaN     NaN                       NaN NaN NaN

[7468 rows x 22 columns]

In [5]:
from apyori import apriori
anmol_intelligence = apriori (transactions = transactions, min_support = 0.002 , min_confidence = 0.2 , min_lift = 1 , min_length = 2)

In [6]:
results = list(anmol_intelligence)
results

[RelationRecord(items=frozenset({'The Dark Knight'}), support=0.2390838467720332, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'The Dark Knight'}), confidence=0.2390838467720332, lift=1.0)]),
 RelationRecord(items=frozenset({'nan'}), support=0.9998660594695955, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=0.9998660594695955, lift=1.0)]),
 RelationRecord(items=frozenset({'12 Angry Men', 'Pulp Fiction'}), support=0.01687650683096705, ordered_statistics=[OrderedStatistic(items_base=frozenset({'12 Angry Men'}), items_add=frozenset({'Pulp Fiction'}), confidence=0.22066549912434327, lift=1.2313068882379274)]),
 RelationRecord(items=frozenset({'12 Angry Men', 'The Dark Knight'}), support=0.02410929547281007, ordered_statistics=[OrderedStatistic(items_base=frozenset({'12 Angry Men'}), items_add=frozenset({'The Dark Knight'}), confidence=0.3152364273204904, lift=1.3185183004900736)]),
 RelationRecord(items=frozenset({'The Dark Knight', '2001: A Space Odyssey'}), support=0.004420037503348513, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2001: A Space Odyssey'}), items_add=frozenset({'The Dark Knight'}), confidence=0.2661290322580645, lift=1.1131200867443751)]),
 RelationRecord(items=frozenset({'The Intouchables', '2001: A Space Odyssey'}), support=0.0034824537905170103, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2001: A Space Odyssey'}), items_add=frozenset({'The Intouchables'}), confidence=0.2096774193548387, lift=1.615533140251007)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Fellowship of the Ring', '2001: A Space Odyssey'}), support=0.004553978033753014, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2001: A Space Odyssey'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.27419354838709675, lift=1.5686812507724632)]),
 RelationRecord(items=frozenset({'The Silence of the Lambs', '2001: A Space Odyssey'}), support=0.0034824537905170103, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2001: A Space Odyssey'}), items_add=frozenset({'The Silence of the Lambs'}), confidence=0.2096774193548387, lift=1.2747977303772198)]),
 RelationRecord(items=frozenset({'nan', '2001: A Space Odyssey'}), support=0.01660862577015805, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2001: A Space Odyssey'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'The Dark Knight', '3 Idiots'}), support=0.0021430484864720066, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3 Idiots'}), items_add=frozenset({'The Dark Knight'}), confidence=0.3076923076923077, lift=1.2869640163757812)]),
 RelationRecord(items=frozenset({'The Pianist', '3 Idiots'}), support=0.0021430484864720066, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3 Idiots'}), items_add=frozenset({'The Pianist'}), confidence=0.3076923076923077, lift=3.2264477095937774)]),
 RelationRecord(items=frozenset({'3 Idiots', 'nan'}), support=0.006964907581034021, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3 Idiots'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'Alien', 'The Dark Knight'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Alien'}), items_add=frozenset({'The Dark Knight'}), confidence=0.41379310344827586, lift=1.7307447116777745)]),
 RelationRecord(items=frozenset({'Alien', 'The Intouchables'}), support=0.002276989016876507, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Alien'}), items_add=frozenset({'The Intouchables'}), confidence=0.29310344827586204, lift=2.2583182093163945)]),
 RelationRecord(items=frozenset({'Alien', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.003750334851326011, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Alien'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.48275862068965514, lift=2.7618972123133836)]),
 RelationRecord(items=frozenset({'Alien', 'nan'}), support=0.0077685507634610235, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Alien'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'Aliens'}), support=0.0025448700776855076, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Aliens'}), items_add=frozenset({'The Dark Knight'}), confidence=0.3653846153846154, lift=1.5282697694462402)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Return of the King', 'Aliens'}), support=0.0021430484864720066, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Aliens'}), items_add=frozenset({'The Lord of the Rings: The Return of the King'}), confidence=0.3076923076923077, lift=1.7947115384615386)]),
 RelationRecord(items=frozenset({'Amadeus ', 'The Dark Knight'}), support=0.0021430484864720066, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Amadeus '}), items_add=frozenset({'The Dark Knight'}), confidence=0.3478260869565218, lift=1.4548288880769702)]),
 RelationRecord(items=frozenset({'Amadeus ', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.0024109295472810074, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Amadeus '}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.391304347826087, lift=2.238680659670165)]),
 RelationRecord(items=frozenset({'Amadeus ', 'nan'}), support=0.0061612643986070185, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Amadeus '}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'American Beauty ', 'nan'}), support=0.004821859094562015, ordered_statistics=[OrderedStatistic(items_base=frozenset({'American Beauty '}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'American History X', 'The Good, the Bad and the Ugly'}), support=0.002009107956067506, ordered_statistics=[OrderedStatistic(items_base=frozenset({'American History X'}), items_add=frozenset({'The Good, the Bad and the Ugly'}), confidence=0.2586206896551724, lift=3.2181034482758615)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Return of the King', 'American History X'}), support=0.002678810608090008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'American History X'}), items_add=frozenset({'The Lord of the Rings: The Return of the King'}), confidence=0.3448275862068965, lift=2.0113146551724137)]),
 RelationRecord(items=frozenset({'Whiplash', 'American History X'}), support=0.002276989016876507, ordered_statistics=[OrderedStatistic(items_base=frozenset({'American History X'}), items_add=frozenset({'Whiplash'}), confidence=0.29310344827586204, lift=2.2126494892088835)]),
 RelationRecord(items=frozenset({'American History X', 'nan'}), support=0.0077685507634610235, ordered_statistics=[OrderedStatistic(items_base=frozenset({'American History X'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'Apocalypse Now', 'The Dark Knight'}), support=0.009241896597910528, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Apocalypse Now'}), items_add=frozenset({'The Dark Knight'}), confidence=0.28512396694214875, lift=1.1925689283978054)]),
 RelationRecord(items=frozenset({'Apocalypse Now', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.008706134476292525, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Apocalypse Now'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.26859504132231404, lift=1.5366517843006873)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Return of the King', 'Apocalypse Now'}), support=0.0073667291722475225, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Apocalypse Now'}), items_add=frozenset({'The Lord of the Rings: The Return of the King'}), confidence=0.2272727272727273, lift=1.3256392045454548)]),
 RelationRecord(items=frozenset({'Whiplash', 'Apocalypse Now'}), support=0.00669702652022502, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Apocalypse Now'}), items_add=frozenset({'Whiplash'}), confidence=0.2066115702479339, lift=1.5597188912751003)]),
 RelationRecord(items=frozenset({'Apocalypse Now', 'nan'}), support=0.0324136083578891, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Apocalypse Now'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'Avengers: Endgame', 'nan'}), support=0.004420037503348513, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Avengers: Endgame'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'Avengers: Infinity War', 'The Dark Knight'}), support=0.007902491293865523, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Avengers: Infinity War'}), items_add=frozenset({'The Dark Knight'}), confidence=0.30569948186528495, lift=1.2786287572023627)]),
 RelationRecord(items=frozenset({'Avengers: Infinity War', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.005625502276989017, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Avengers: Infinity War'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.21761658031088085, lift=1.2450002977785721)]),
 RelationRecord(items=frozenset({'Avengers: Infinity War', 'The Lord of the Rings: The Return of the King'}), support=0.005625502276989017, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Avengers: Infinity War'}), items_add=frozenset({'The Lord of the Rings: The Return of the King'}), confidence=0.21761658031088085, lift=1.26931670984456)]),
 RelationRecord(items=frozenset({'Back to the Future', 'The Dark Knight'}), support=0.025314760246450577, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Back to the Future'}), items_add=frozenset({'The Dark Knight'}), confidence=0.3258620689655173, lift=1.3629614604462477)]),
 RelationRecord(items=frozenset({'Back to the Future', 'The Dark Knight Rises'}), support=0.0028127511384945084, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Dark Knight Rises'}), items_add=frozenset({'Back to the Future'}), confidence=0.2079207920792079, lift=2.6764424718333903)]),
 RelationRecord(items=frozenset({'Back to the Future', 'The Intouchables'}), support=0.017010447361371552, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Back to the Future'}), items_add=frozenset({'The Intouchables'}), confidence=0.21896551724137933, lift=1.6870965446069537)]),
 RelationRecord(items=frozenset({'Back to the Future', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.01995713903027056, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Back to the Future'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.25689655172413794, lift=1.4697238736953364)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Return of the King', 'Back to the Future'}), support=0.017010447361371552, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Back to the Future'}), items_add=frozenset({'The Lord of the Rings: The Return of the King'}), confidence=0.21896551724137933, lift=1.277184806034483)]),
 RelationRecord(items=frozenset({'Back to the Future', 'The Silence of the Lambs'}), support=0.017948031074203053, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Back to the Future'}), items_add=frozenset({'The Silence of the Lambs'}), confidence=0.2310344827586207, lift=1.404644501853308)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'Bicycle Thieves'}), support=0.0034824537905170103, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Bicycle Thieves'}), items_add=frozenset({'The Dark Knight'}), confidence=0.3661971830985915, lift=1.531668442024697)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Fellowship of the Ring', 'Bicycle Thieves'}), support=0.0030806321993035093, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Bicycle Thieves'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.32394366197183094, lift=1.8533052722465058)]),
 RelationRecord(items=frozenset({'The Silence of the Lambs', 'Bicycle Thieves'}), support=0.0028127511384945084, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Bicycle Thieves'}), items_add=frozenset({'The Silence of the Lambs'}), confidence=0.29577464788732394, lift=1.7982520530348214)]),
 RelationRecord(items=frozenset({'Bicycle Thieves', 'nan'}), support=0.009509777658719529, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Bicycle Thieves'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'Pulp Fiction', 'Billa'}), support=0.021832306455933564, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa'}), items_add=frozenset({'Pulp Fiction'}), confidence=0.22797202797202795, lift=1.2720771007766523)]),
 RelationRecord(items=frozenset({'Saaho', 'Billa'}), support=0.005491561746584516, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Saaho'}), items_add=frozenset({'Billa'}), confidence=0.2751677852348993, lift=2.8732904679213402)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'Billa'}), support=0.035896062148406106, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa'}), items_add=frozenset({'The Dark Knight'}), confidence=0.3748251748251748, lift=1.5677561654032242)]),
 RelationRecord(items=frozenset({'The Intouchables', 'Billa'}), support=0.02370747388159657, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa'}), items_add=frozenset({'The Intouchables'}), confidence=0.24755244755244754, lift=1.9073545649397043)]),
 RelationRecord(items=frozenset({'The Lion King', 'Billa'}), support=0.01620680417894455, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Lion King'}), items_add=frozenset({'Billa'}), confidence=0.23586744639376217, lift=2.4629179787074524)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Fellowship of the Ring', 'Billa'}), support=0.027993570854540583, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.2923076923076923, lift=1.6723135867963457)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Return of the King', 'Billa'}), support=0.01915349584784356, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa'}), items_add=frozenset({'The Lord of the Rings: The Return of the King'}), confidence=0.2, lift=1.1665625000000002)]),
 RelationRecord(items=frozenset({'The Lord of the rings', 'Billa'}), support=0.01674256630056255, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Lord of the rings'}), items_add=frozenset({'Billa'}), confidence=0.2332089552238806, lift=2.435158125456633)]),
 RelationRecord(items=frozenset({'The Shining', 'Billa'}), support=0.0021430484864720066, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Shining'}), items_add=frozenset({'Billa'}), confidence=0.23529411764705885, lift=2.4569313039901277)]),
 RelationRecord(items=frozenset({'The Silence of the Lambs', 'Billa'}), support=0.02303777122957407, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa'}), items_add=frozenset({'The Silence of the Lambs'}), confidence=0.24055944055944056, lift=1.4625543837270223)]),
 RelationRecord(items=frozenset({'Billa', 'nan'}), support=0.09576747923921779, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'Black Panther', 'Captain America'}), support=0.00334851326011251, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Captain America'}), items_add=frozenset({'Black Panther'}), confidence=0.24509803921568626, lift=5.140174047146949)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'Black Panther'}), support=0.015135279935708545, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Black Panther'}), items_add=frozenset({'The Dark Knight'}), confidence=0.31741573033707865, lift=1.3276335253202405)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Fellowship of the Ring', 'Black Panther'}), support=0.011920707206000535, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Black Panther'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.25, lift=1.4302681992337165)]),
 RelationRecord(items=frozenset({'Pulp Fiction', 'Braveheart'}), support=0.008706134476292525, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Braveheart'}), items_add=frozenset({'Pulp Fiction'}), confidence=0.20123839009287922, lift=1.122904200622897)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'Braveheart'}), support=0.01339405304045004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Braveheart'}), items_add=frozenset({'The Dark Knight'}), confidence=0.30959752321981426, lift=1.2949328338146406)]),
 RelationRecord(items=frozenset({'Braveheart', 'The Intouchables'}), support=0.009241896597910528, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Braveheart'}), items_add=frozenset({'The Intouchables'}), confidence=0.21362229102167182, lift=1.6459277861380825)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Fellowship of the Ring', 'Braveheart'}), support=0.009107956067506027, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Braveheart'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.21052631578947367, lift=1.204436378302077)]),
 RelationRecord(items=frozenset({'The Silence of the Lambs', 'Braveheart'}), support=0.009509777658719529, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Braveheart'}), items_add=frozenset({'The Silence of the Lambs'}), confidence=0.21981424148606812, lift=1.336427627797219)]),
 RelationRecord(items=frozenset({'Braveheart', 'nan'}), support=0.04326279132065363, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Braveheart'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001339584728735)]),
 RelationRecord(items=frozenset({'Pulp Fiction', 'Capernaum'}), support=0.0073667291722475225, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Capernaum'}), items_add=frozenset({'Pulp Fiction'}), confidence=0.2173913043478261, lift=1.2130369792682136)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'Capernaum'}), support=0.00964371818912403, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Capernaum'}), items_add=frozenset({'The Dark Knight'}), confidence=0.2845849802371542, lift=1.1903145447902483)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Fellowship of the Ring', 'Capernaum'}), support=0.0073667291722475225, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Capernaum'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.2173913043478261, lift=1.2437114775945364)]),
 RelationRecord(items=frozenset({'The Lord of the Rings: The Return of the King', 'Capernaum'}), support=0.007902491293865523, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Capernaum'}), items_add=frozenset({'The Lord of the Rings: The Return of the King'}), confidence=0.23320158102766797, lift=1.3602210968379447)]),

In [7]:
def inspect(results):
    rows = []
    
    for result in results:
        for stat in result.ordered_statistics:
            
            if len(stat.items_base) > 0 and len(stat.items_add) > 0:
                
                movie1 = list(stat.items_base)[0]
                movie2 = list(stat.items_add)[0]
                support = result.support
                confidence = stat.confidence
                lift = stat.lift
                
                rows.append((movie1, movie2, support, confidence, lift))
    
    return rows

In [8]:
DataFrame_intelligence = pd.DataFrame(
    inspect(results),
    columns=['Movie1','Movie2','Support','Confidence','Lift']
)

DataFrame_intelligence

,Movie1,Movie2,Support,Confidence,Lift
0,12 Angry Men,Pulp Fiction,0.016877,0.220665,1.231307
1,12 Angry Men,The Dark Knight,0.024109,0.315236,1.318518
2,2001: A Space Odyssey,The Dark Knight,0.004420,0.266129,1.113120
3,2001: A Space Odyssey,The Intouchables,0.003482,0.209677,1.615533
4,2001: A Space Odyssey,The Lord of the Rings: The Fellowship of the Ring,0.004554,0.274194,1.568681
...,...,...,...,...,...
11301,The Silence of the Lambs,inception,0.002009,0.500000,5.072011
11302,The Dark Knight,The Silence of the Lambs,0.002009,0.535714,3.257038
11303,The Silence of the Lambs,The Intouchables,0.002009,0.600000,4.622910
11304,The Silence of the Lambs,The Dark Knight,0.002009,0.750000,3.136975
11305,The Silence of the Lambs,Billa,0.002009,0.600000,6.265175

In [9]:
DataFrame_intelligence.head()

,Movie1,Movie2,Support,Confidence,Lift
0,12 Angry Men,Pulp Fiction,0.016877,0.220665,1.231307
1,12 Angry Men,The Dark Knight,0.024109,0.315236,1.318518
2,2001: A Space Odyssey,The Dark Knight,0.004420,0.266129,1.113120
3,2001: A Space Odyssey,The Intouchables,0.003482,0.209677,1.615533
4,2001: A Space Odyssey,The Lord of the Rings: The Fellowship of the Ring,0.004554,0.274194,1.568681

In [10]:
#Sort the Best Recommendations. Show strongest rules first.
DataFrame_intelligence = DataFrame_intelligence.sort_values(
    by="Lift", ascending=False
)

In [11]:
DataFrame_intelligence.head(10)

,Movie1,Movie2,Support,Confidence,Lift
1975,Harry Potter 2,Harry Potter 1,0.002545,0.441860,28.195985
6625,Harry Potter 2,Harry Potter 1,0.002545,0.441860,28.195985
6629,Harry Potter 2,Harry Potter 1,0.002545,0.441860,28.195985
1973,Harry Potter 2,crimes of grindelwald,0.002545,0.441860,23.069442
6623,Harry Potter 2,crimes of grindelwald,0.002545,0.441860,23.069442
6627,Harry Potter 2,crimes of grindelwald,0.002545,0.441860,23.069442
6628,Harry Potter 1,Harry Potter 2,0.002545,0.950000,12.001184
6624,Harry Potter 1,Harry Potter 2,0.002545,0.950000,12.001184
1974,Harry Potter 1,Harry Potter 2,0.002545,0.950000,12.001184
9843,Comedy nights with Kapil,The Lord of the Rings: The Fellowship of the Ring,0.002143,0.296296,10.584441

In [12]:
DataFrame_intelligence = DataFrame_intelligence.replace('nan', np.nan)

In [13]:
#Remove rows where Movie1 or Movie2 is NaN
DataFrame_intelligence = DataFrame_intelligence.dropna(subset=['Movie1','Movie2'])

In [14]:
DataFrame_intelligence.head(10)

,Movie1,Movie2,Support,Confidence,Lift
1975,Harry Potter 2,Harry Potter 1,0.002545,0.441860,28.195985
6625,Harry Potter 2,Harry Potter 1,0.002545,0.441860,28.195985
6629,Harry Potter 2,Harry Potter 1,0.002545,0.441860,28.195985
1973,Harry Potter 2,crimes of grindelwald,0.002545,0.441860,23.069442
6623,Harry Potter 2,crimes of grindelwald,0.002545,0.441860,23.069442
6627,Harry Potter 2,crimes of grindelwald,0.002545,0.441860,23.069442
6628,Harry Potter 1,Harry Potter 2,0.002545,0.950000,12.001184
6624,Harry Potter 1,Harry Potter 2,0.002545,0.950000,12.001184
1974,Harry Potter 1,Harry Potter 2,0.002545,0.950000,12.001184
9843,Comedy nights with Kapil,The Lord of the Rings: The Fellowship of the Ring,0.002143,0.296296,10.584441

In [15]:
DataFrame_intelligence = DataFrame_intelligence.drop_duplicates()

In [16]:
DataFrame_intelligence = DataFrame_intelligence.sort_values(by="Lift", ascending=False)

In [17]:
DataFrame_intelligence.head(10)

,Movie1,Movie2,Support,Confidence,Lift
1975,Harry Potter 2,Harry Potter 1,0.002545,0.441860,28.195985
1973,Harry Potter 2,crimes of grindelwald,0.002545,0.441860,23.069442
6628,Harry Potter 1,Harry Potter 2,0.002545,0.950000,12.001184
9843,Comedy nights with Kapil,The Lord of the Rings: The Fellowship of the Ring,0.002143,0.296296,10.584441
10029,The Silence of the Lambs,inception,0.002009,0.205479,9.297634
10034,inception,The Dark Knight,0.002009,0.326087,9.084199
9953,Billa,The Intouchables,0.003081,0.383333,7.972052
5151,Billa,The Dark Knight,0.003081,0.383333,7.972052
10313,Comedy nights with Kapil,The Lord of the Rings: The Fellowship of the Ring,0.002009,0.277778,7.796575
10227,The Lord of the rings,The Lord of the Rings: The Fellowship of the Ring,0.002411,0.209302,7.476800

In [18]:
DataFrame_intelligence = DataFrame_intelligence.reset_index(drop=True)

In [19]:
DataFrame_intelligence.head(10)

,Movie1,Movie2,Support,Confidence,Lift
0,Harry Potter 2,Harry Potter 1,0.002545,0.441860,28.195985
1,Harry Potter 2,crimes of grindelwald,0.002545,0.441860,23.069442
2,Harry Potter 1,Harry Potter 2,0.002545,0.950000,12.001184
3,Comedy nights with Kapil,The Lord of the Rings: The Fellowship of the Ring,0.002143,0.296296,10.584441
4,The Silence of the Lambs,inception,0.002009,0.205479,9.297634
5,inception,The Dark Knight,0.002009,0.326087,9.084199
6,Billa,The Intouchables,0.003081,0.383333,7.972052
7,Billa,The Dark Knight,0.003081,0.383333,7.972052
8,Comedy nights with Kapil,The Lord of the Rings: The Fellowship of the Ring,0.002009,0.277778,7.796575
9,The Lord of the rings,The Lord of the Rings: The Fellowship of the Ring,0.002411,0.209302,7.476800

In [20]:
DataFrame_intelligence.to_csv("movie_rules.csv", index=False)

In [21]:
def recommend(movie):

    result = DataFrame_intelligence[
        DataFrame_intelligence["Movie1"] == movie
    ][["Movie2","Confidence","Lift"]]

    result = result.drop_duplicates(subset=["Movie2"])

    result = result.sort_values(by="Lift", ascending=False)

    return result.head(10)

In [22]:
recommend("Billa")

                                                 Movie2  Confidence      Lift
6                                      The Intouchables    0.383333  7.972052
7                                       The Dark Knight    0.383333  7.972052
127   The Lord of the Rings: The Fellowship of the Ring    0.250000  4.175615
144                            Comedy nights with Kapil    0.266667  4.038404
242                                       The Lion King    0.250000  3.638402
395                                           inception    0.316667  3.212274
2872                           The Silence of the Lambs    0.266667  1.621281
2970                                       Pulp Fiction    0.283333  1.580992
3821      The Lord of the Rings: The Return of the King    0.200000  1.166563

In [23]:
# load rules
DataFrame_intelligence = pd.read_csv("movie_rules.csv")

In [24]:
def recommend(movie):

    result = DataFrame_intelligence[
        DataFrame_intelligence["Movie1"].str.lower() == movie.lower()
    ][["Movie2","Confidence","Lift"]]

    if result.empty:
        return "No recommendation found."

    result = result.drop_duplicates(subset=["Movie2"])

    result = result.sort_values(by="Lift", ascending=False)

    return result.head(10)

In [25]:
recommend("Billa")

                                                 Movie2  Confidence      Lift
6                                      The Intouchables    0.383333  7.972052
7                                       The Dark Knight    0.383333  7.972052
127   The Lord of the Rings: The Fellowship of the Ring    0.250000  4.175615
144                            Comedy nights with Kapil    0.266667  4.038404
242                                       The Lion King    0.250000  3.638402
395                                           inception    0.316667  3.212274
2872                           The Silence of the Lambs    0.266667  1.621281
2970                                       Pulp Fiction    0.283333  1.580992
3821      The Lord of the Rings: The Return of the King    0.200000  1.166563

In [26]:
def check_relation(movie1, movie2):

    result = DataFrame_intelligence[
        (DataFrame_intelligence["Movie1"].str.lower() == movie1.lower()) &
        (DataFrame_intelligence["Movie2"].str.lower() == movie2.lower())
    ][["Support","Confidence","Lift"]]

    if result.empty:
        return "No strong relation found."

    # choose strongest rule
    result = result.sort_values(by="Lift", ascending=False)

    return result.head(1)

In [27]:
check_relation("Billa","Inception")

      Support  Confidence      Lift
395  0.002545    0.316667  3.212274

In [28]:
import pandas as pd
import pickle

# load rule table
rules = pd.read_csv("movie_rules.csv")


class MovieRecommender:

    def __init__(self, rules):
        self.rules = rules

    def recommend(self, movie):

        result = self.rules[
            self.rules["Movie1"].str.lower() == movie.lower()
        ][["Movie2","Confidence","Lift"]]

        result = result.drop_duplicates(subset=["Movie2"])
        result = result.sort_values(by="Lift", ascending=False)

        return result.head(10)

    def relation(self, movie1, movie2):

        result = self.rules[
            (self.rules["Movie1"].str.lower() == movie1.lower()) &
            (self.rules["Movie2"].str.lower() == movie2.lower())
        ][["Support","Confidence","Lift"]]

        if result.empty:
            return "No strong relation found"

        result = result.sort_values(by="Lift", ascending=False)

        return result.head(1)


# create object
model = MovieRecommender(rules)

# save model
pickle.dump(model, open("movie_model.pkl","wb"))

In [29]:
import pickle

model = pickle.load(open("movie_model.pkl","rb"))

In [30]:
model.recommend("Billa")

                                                 Movie2  Confidence      Lift
6                                      The Intouchables    0.383333  7.972052
7                                       The Dark Knight    0.383333  7.972052
127   The Lord of the Rings: The Fellowship of the Ring    0.250000  4.175615
144                            Comedy nights with Kapil    0.266667  4.038404
242                                       The Lion King    0.250000  3.638402
395                                           inception    0.316667  3.212274
2872                           The Silence of the Lambs    0.266667  1.621281
2970                                       Pulp Fiction    0.283333  1.580992
3821      The Lord of the Rings: The Return of the King    0.200000  1.166563

In [31]:
model.relation("Billa","Inception")

      Support  Confidence      Lift
395  0.002545    0.316667  3.212274

In [32]:
#final test
import pickle

model = pickle.load(open("movie_model.pkl","rb"))

# Test recommend
print(model.recommend("Avatar"))

# Test relation
print(model.relation("Avatar", "Titanic"))

Empty DataFrame
Columns: [Movie2, Confidence, Lift]
Index: []
No strong relation found